name: Terraform Plan (dev)

on:
  pull_request:
    paths:
      - '**/*.tf'
      - 'envs/dev/**'
      - '.github/workflows/**'

permissions:
  id-token: write      # <-- required for OIDC
  contents: read

env:
  WORKDIR: envs/dev/ap-southeast-1

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: amithcm/eks-infra         # ðŸ‘ˆ replace with your org/repo
          path: eks-infra

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        working-directory: eks-infra/${{ env.WORKDIR }}
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: eks-infra/${{ env.WORKDIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: eks-infra/${{ env.WORKDIR }}
        run: terraform plan -no-color -input=false
